config/routes.rb
Rails.application.routes.draw do
  get 'vehicles/all'
  resources :vehicles
  devise_for :users
  get 'pages/index'
  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@vehicles = Vehicle.all
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @vehicles = Vehicle.all.where(for_sale: true)
  # add in later w/ will_paginate: .paginate(:page => params[:page], :per_page => 10)
  end

  def all
    @vehicles = Vehicle.all
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: "The vehicle was created succesfully." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: "The vehicle was updated succesfully." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def destroy
    @vehicle.destroy
    redirect_to root_path, notice: "The vehicle  was succesfully marked as sold."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow trusted parameters
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :year, :mileage, :interior_color, :exterior_color, :condition, :description, :price, :for_sale)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
	def button_text_vehicles
		if controller.action_name == "new"
			return "Add this Vehicle to Inventory"
		elsif controller.action_name == "edit"
			return "Edit Vehicle Information"
		else
			return "Add A Vehicle"
		end
	end

	def inventory_title
		if controller.action_name == "index"
			return "Vehicles For Sale"
		elsif controller.action_name = "all"
			return "All Vehicles, Sold and Unsold"
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECMC Inventory Tracking Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= render('shared/nav') %>
    <%= render('shared/alerts') %>

  	<div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/index.html.erb
<%= render('vehicles/vehicles') %>

app/views/shared/_alerts.html.erb
<% if notice || alert %>
	<div class="notification is-link">
		<button class="delete" onClick="closeNotification();"></button>
			<% if notice %>
				<p class="notice"><%= notice %></p>
			<% end %>
			
			<% if alert %>
				<p class="alert"><%= alert %></p>
			<% end %>
	</div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar is-transparent">
  <div class="navbar-brand">
     <%= link_to image_tag("logo.png", width: 163, height: 81), pages_index_path, {class: 'navbar-item'} %>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <% if user_signed_in? %>
          <%= link_to "Inventory For Sale", vehicles_path, class: "navbar-item" %>
          <%= link_to('All Vehicles', vehicles_all_path, class: "navbar-item") %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "navbar-item") %>

      <% else %>
          <%= link_to "Log In", new_user_session_path, class: "navbar-item" %>
      <% end %>
  </div>
</nav>

app/views/vehicles/_form.html.erb
<%= form_with(model: @vehicle, local: true) do |form| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label "Make" %></strong>
    <%= form.text_field :make, id: :make, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <strong><%= form.label "Model" %></strong>
    <%= form.text_field :model, id: :model, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <strong><%= form.label "Year" %></strong>
    <%= form.number_field :year, id: :year, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <strong><%= form.label "Mileage" %></strong>
    <%= form.number_field :mileage, id: :mileage, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <strong><%= form.label "Interior Color"  %></strong>
    <%= form.text_field :interior_color, id: :interior_color, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <strong><%= form.label "Exterior Color"  %></strong>
    <%= form.text_field :exterior_color, id: :exterior_color, class: "input is-medium" %>
  </div>
  
  <br>

  <div class="field">
    <strong><%= form.label "Condition" %></strong>
    <%= form.text_field :condition, id: :condition, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <strong><%= form.label "Price" %></strong>
    <%= form.number_field :price, id: :price, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <label class="checkbox">
    <%= form.check_box :for_sale, id: :for_sale %>
     <strong>Vehicle Currently For Sale</strong>
    </label>

    <p>
      Default value is FOR SALE. Uncheck this box to indicate the vehicle is sold or is no longer available in the FOR SALE inventory.
    </p>
  </div>

  <div class="field">
    <strong><%= form.label "Description of Vehicle, Other Information not available via other form inputs."  %></strong>
    <%= form.text_area :description, id: :description, class: "textarea is-medium" %>
  </div>

  <hr>

  <div class="actions">
    <%= form.submit button_text_vehicles, class: "button is-medium" %>
  </div>
<% end %>

app/views/vehicles/_full_list.html.erb
<table class="table is-hover is-fullwidth is-responsive">
	<thead>
		<tr>
			<th>Vehicle</th>
			<th>Mileage</th>
			<th>Price</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @vehicles.each do |vehicle| %>
		<tr>
			<td><%= vehicle.year %> <%= vehicle.make %> <%= vehicle.model %></td>
			<td><%= vehicle.mileage %> </td>
			<td>$<%= vehicle.price %></td>
			<td><%= link_to 'Show', vehicle, class: 'button is-small' %></td>
      <td><%= link_to 'Edit', edit_vehicle_path(vehicle), class: 'button is-small' %></td>
      <td>
      	<%= link_to 'Destroy', vehicle,  method: :delete, class: "button is-small", data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/vehicles/_vehicles.html.erb
<h1><%= icon('flag-checkered') %> Emerald Coast Motor Cars</h1>
<h2><%= icon('car') %> <%= inventory_title %></h2>
<hr>
<div class="columns is-mobile">
	<div class="column">
		<%= render('vehicles/full_list') %>
	</div>
</div>

<%= link_to icon('car') + ' ' + button_text_vehicles, new_vehicle_path, class: "" %>

app/views/vehicles/all.html.erb
<%= render('vehicles/vehicles') %>

app/views/vehicles/edit.html.erb
<h2>Edit Vehicle</h2>

<%= render ('form') %>

<%= link_to "Back to All Vehicle Listings View.", vehicles_path %>

app/views/vehicles/index.html.erb
<%= render('vehicles/vehicles') %>

app/views/vehicles/new.html.erb
<h1><%= icon('flag-checkered') %> Add a Vehicle to Your Inventory</h1>
<%= render('form') %>
<br>
<%= link_to 'Back', vehicles_path, class: "button is-link" %>

app/views/vehicles/show.html.erb
<div class="card is-centered">
  <header class="card-header">
		<h2 class="card-header-title title">
			<%= @vehicle.year %> 
			<%= @vehicle.make %>
			<%= @vehicle.model %> 
		</h2>
	</header>
	<div class="card-content">
		<p class="subtitle is-6">
			LAST UPDATED <%= @vehicle.created_at.strftime('%m/%d/%Y') %>	
		</p>
		<strong>Price: </strong>$<%= @vehicle.price %>
		<br>
		<strong>Mileage: </strong><%= @vehicle.mileage %>
		<br>
		<strong>Interior Color: </strong><%= @vehicle.interior_color %>
		<br>
		<strong>Exterior Color: </strong><%= @vehicle.exterior_color %>
		<br>
		<strong>Condition: </strong><%= @vehicle.condition %>
		<br>
		<br>
		
		<strong>Description for Advertisement: </strong><br>
		<%= @vehicle.description %>
		<hr>
		<%= link_to 'Edit', edit_vehicle_path(@vehicle), class: "button is-rounded" %>
		<%= link_to 'Back', vehicles_path, class: "button is-rounded" %>
	</div>
</div>